_target_: t4c22.core.models.baselines.T4c22GNN

in_node_features: 4
in_edge_features: 5  # len ${dataset.edge_attributes}
hidden_features: 150
out_features: 3  # 3 congestion classes (green, yellow, red)
gnn_layer_num: 6
dropout_p: 0.6
