root: ${data_path}
cities:
  - london
  - melbourne
  - madrid
edge_attributes:
  - parsed_maxspeed
  - importance
  - length_meters
  - counter_distance
  - oneway
  - lanes
  - tunnel
  # categorical
  - highway
cachedir: ${data_path}/cachedir/

train:
  _target_: t4c22.core.dataset.T4c22STILDataset

  root: ${dataset.root}
  edge_attributes: ${dataset.edge_attributes}

  cachedir: ${dataset.cachedir}
  limit_ratio: 0.25
  split: train

test:
  _target_: t4c22.core.dataset.T4c22STILDataset

  root: ${dataset.root}
  edge_attributes: ${dataset.edge_attributes}

  cachedir: ${dataset.cachedir}
  split: test
