root: ${data_path}
cities:
  - london
  - melbourne
  - madrid

edge_attributes:
  - parsed_maxspeed
  - importance
  - oneway
  - length_meters
  - counter_distance
  #  - highway
  #  - lanes
  #  - tunnel
cachedir: ${data_path}/cachedir/

train:
  _target_: t4c22.core.dataset.T4c22TrainDataset

  root: ${dataset.root}
  edge_attributes: ${dataset.edge_attributes}

  cachedir: ${dataset.cachedir}
  limit_ratio: 0.25

test:
  _target_: t4c22.dataloading.t4c22_dataset_geometric.T4c22GeometricDataset

  root: ${dataset.root}
  edge_attributes: ${dataset.edge_attributes}

  split: "test"
  cachedir: ${dataset.cachedir}
