author: "Girdyuk Dmitry <girdyuk.dmitry@gmail.com>"
experiment: "test0"
version_base: "0.0.1"

defaults:
  - _self_
  - model: basic_model
  - dataset: basic_dataset

hydra_dir: ../../results/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
hydra:
  run:
    dir: ${hydra_dir}
  job:
    chdir: True

data_path: D:/Data/traffic4cast/2022/raw
checkpoint_save_folder: checkpoints/

city: "london"  # london madrid melbourne
seed: 3141592
epoch_num: 10
num_workers: 0

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005
  weight_decay: 0.001

loss_function:
  _target_: torch.nn.CrossEntropyLoss

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 2
  gamma: 0.9

accelerator:
  _target_: accelerate.accelerator.Accelerator

  cpu: false
  mixed_precision: "no"  # "no","fp16","bf16"
  gradient_accumulation_steps: 1
  # TODO: tensorboard for some reason isn't working
#  log_with: "tensorboard"
#  logging_dir: ${hydra_dir}/tensorboard/
