author: "Girdyuk Dmitry <girdyuk.dmitry@gmail.com>"
submission_name: "full_dropout"
version: "0.0.1"

defaults:
  - _self_
  - model: basic_model
  - dataset: basic_dataset

results_dir: D:\projects\NeurIPS2022-traffic4cast
hydra_dir: ${results_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
hydra:
  run:
    dir: ${hydra_dir}
  job:
    chdir: True

data_path: D:\projects\NeurIPS2022-traffic4cast\data
clear_cachedir: false

seed: 3141592
epoch_num: 15
num_workers: 4
train_val_split: 0.75

pretrained: false

checkpoint_dir: ${results_dir}/models
checkpoint_name: model_checkpoint_best
split_city_models: false

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.00001

loss_function:
  _target_: torch.nn.CrossEntropyLoss

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 1
  gamma: 0.8

accelerator:
  _target_: accelerate.accelerator.Accelerator

  cpu: true
  mixed_precision: "no"  # "no","fp16","bf16"
  gradient_accumulation_steps: 1

checkpoint_saver:
  _target_: t4c22.core.checkpointer.CheckpointSaver
  metric_name: "validation"
  max_history: 3
  should_minimize: true
  save_dir: checkpoints/
