author: "Girdyuk Dmitry <girdyuk.dmitry@gmail.com>"
submission_name: "test"
version: "0.0.1"

defaults:
  - _self_
  - model: basic_model
  - dataset: basic_dataset

results_dir: C:\Users\Girdyuk\Documents\projects\NeurIPS2022-traffic4cast\results\
hydra_dir: ${results_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
hydra:
  run:
    dir: ${hydra_dir}
  job:
    chdir: True

data_path: C:\data\t4c22\raw\
clear_cachedir: false

seed: 3141592
epoch_num: 15
num_workers: 4
train_val_split: 0.75

pretrained: false
checkpoint_path: ${results_dir}/models/model_checkpoint_best.pt

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.01
  weight_decay: 0.0001

loss_function:
  _target_: t4c22.core.loss.T4c22CrossEntropyLoss

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 1
  gamma: 0.7

accelerator:
  _target_: accelerate.accelerator.Accelerator

  cpu: false
  mixed_precision: "fp16"  # "no","fp16","bf16"
  gradient_accumulation_steps: 1

checkpoint_saver:
  _target_: t4c22.core.checkpointer.CheckpointSaver
  metric_name: "validation"
  max_history: 5
  should_minimize: true
  save_dir: checkpoints/
