author: "Girdyuk Dmitry <girdyuk.dmitry@gmail.com>"
experiment: "test0"
version: "0.0.1"

defaults:
  - _self_
  - model: basic_model
  - dataset: custom_dataset

results_dir: D:/Projects/Python/NeurIPS2022-traffic4cast/results
hydra_dir: ${results_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
hydra:
  run:
    dir: ${hydra_dir}
  job:
    chdir: True

data_path: D:/Data/traffic4cast/2022/raw
clear_cachedir: false

seed: 3141592
epoch_num: 30
num_workers: 0

pretrained: false
checkpoint_path: ${results_dir}/models/model_checkpoint_best.pt

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.0001

loss_function:
  _target_: torch.nn.CrossEntropyLoss

lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 1
  gamma: 0.8

accelerator:
  _target_: accelerate.accelerator.Accelerator
  cpu: false
  mixed_precision: "fp16"  # "no","fp16","bf16"
  gradient_accumulation_steps: 1
  # TODO: tensorboard for some reason isn't working
#  log_with: "tensorboard"
#  logging_dir: ${hydra_dir}/tensorboard/

checkpoint_saver:
  _target_: t4c22.core.checkpointer.CheckpointSaver
  metric_name: "validation"
  max_history: 3
  should_minimize: true
  save_dir: checkpoints/
